# Site settings
encoding: utf-8
title: Arjun's Blog
email: arjunmunji@gmail.com
description: > # this means to ignore newlines until "arjun:"
  Arjun is a Computer Science undergrad and a platform agonistic geek. This is his personal blog.
# baseurl: "/blog"
url: "https://arjun.ninja/blog" # the base hostname & protocol for your site
twitter_username: arjundot
github_username:  arjunnn
snapchat_username: arjun1894
permalink: :title
timezone: Asia/Calcutta


# Build settings

kramdown:
  input: GFM
# markdown: redcarpet
# highlighter: pygments
highlighter: rouge
# highlighter: false
# redcarpet:
  # extensions: ["strikethrough"]

gems:
- jemoji
# - jekyll-mentions
# - jekyll-redirect-from
# - jekyll-sitemap
# - jekyll-feed
