# Site settings
encoding: utf-8
title: Arjun's Blog
email: arjunmunji@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Arjun is a Computer Science undergrad and a platform agonistic geek.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://arjun.ninja" # the base hostname & protocol for your site
twitter_username: arjundot
github_username:  arjunnn

# Build settings
markdown: kramdown
# highlighter: pygments
# highlighter: rouge
highlighter: false

